name: Daily DCA Buy

on:
  schedule:
    - cron: "0 14 * * *" # Daily at 10 AM Eastern (14:00 UTC)
  workflow_dispatch: # Allow manual trigger

jobs:
  dca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run DCA script
        env:
          COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
          COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
        run: python dca.py
